---
- name: Ensure Apache is installed on RHEL.
  package:
    name: "{{ apache_packages }}"
    state: "{{ apache_packages_state }}"
    enablerepo: "{{ apache_enablerepo | default(omit, true) }}"

- name: Copy index file
  copy:
    src: index.html
    dest: "{{ item.documentroot }}"
  with_items: "{{ apache_vhosts }}"
